### ISSUE TITLE
Hackable 40 ?

### ISSUE THREAD

**Issue by Martoni** [Hackable-magazine/Hackable39#2]
Hello,

Il n'y a p as de dépot officiel pour le Hakable 40 ?

En ce qui concerne les articles sur la quickfeather et sur Chisel, les liens vers les sources sont disponibles sur l[e dépot de l'auteur](https://github.com/Martoni/Diamond_HK_GLMF_OS/tree/master/Hackable40) : 

https://github.com/Martoni/Diamond_HK_GLMF_OS/tree/master/Hackable40

**Comment by 0xDRRB** [comment]
En un mot : "oups".
C'est corrigé.

**Comment by Martoni** [comment]
> C'est corrigé.

Vraiment ?
Ou alors c'est un dépot privée ?
